server:
  port: 8080

spring:
  application:
    name: ms-restaurant

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_restaurant
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml